---
name: POE-Component-IRC-Plugin-Unicode-UCD
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: lookup unicode chars/codes from IRC
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  Encode: 2.12
  POE::Component::IRC::Plugin::BaseWrap: 0.001
  Unicode::UCD: 0.24
build_requires:
  Test::More: 0
provides:
  POE::Component::IRC::Plugin::Unicode::UCD:
    file: lib/POE/Component/IRC/Plugin/Unicode/UCD.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
